### ISSUE TITLE
targetPlatform tag not show Joomla version

### ISSUE THREAD

**Issue by pv501977** [SeptdirWorkshop/SWJProjects#64]
File SWJProjects/com_swjprojects/site/models/jupdate.php line 556 shloud be

$targetPlatform->addAttribute('version', $item->joomla_version);

Duplicate tag "tag"
 - same file, line 552 - this line should be deleted

**Comment by Septdir** [comment]
File SWJProjects/com_swjprojects/site/models/jupdate.php line 556 shloud be
```
$targetPlatform->addAttribute('version', $item->joomla_version);
```
I would like it to be so, but it doesn’t work out using the version from the database.
Because the joomla xml file has a very specific indication of the minimum version.
For example, if the version is 3.7.5, then at 3.8.x it may not be installed.
For accuracy, in versions you will have to add min and max dev_level, as well as allow this kind of value.
`3. [012345] | 10`
I came across this a couple of times, so in this case I did not intentionally add a version.

---
```Duplicate tag "tag" ```
Thank you Correct in the next version
