### ISSUE TITLE
SWJProjects 1.5.4 - Image upload error

### ISSUE THREAD

**Issue by joomlaphp** [SeptdirWorkshop/SWJProjects#71]
Hi,
Error uploading images. The other  SW JProjects admin pages have the same error (Category, Projects, Versions).

Steps:

Go to 'swjprojects'
'Category, Projects, Versions' Image upload error
`500 Internal Server Error`

**Note: SW JProjects: Configuration - Options**

- Files folder path : /home/xxxx/public_html/swjprojects (Everything is right)

- Images folder path : images/swjprojects (Everything is right)

Screenshots:

http://kilitlitorba.com/images/images_upload.jpg

System Information:

Joomla version: 3.9.16 stable
**Extensions version [1.5.4]**
PHP version: [7.2.28]
Server OS: [Linux]
Browser [chrome]

Best Regards
Ugur

**Comment by Septdir** [comment]
@joomlaphp I can't reproduce this bug.
Send the full text of the error
Open network tab in browser and look at the response of the request with an error, or look in the server logs, or send me access to the site by email send me email access (admin and files) to the site

**Comment by joomlaphp** [comment]
> @joomlaphp I can't reproduce this bug.
> Send the full text of the error
> Open network tab in browser and look at the response of the request with an error, or look in the server logs, or send me access to the site by email send me email access (admin and files) to the site

Thank you Igor,

I sent the site information to the e-mail address. septdir@gmail.com

Best Regards

**Comment by Septdir** [comment]
@joomlaphp thanks for access.
For correct operation, you need to enable ` fileinfo ` extension in php or make a `mime_content_type` function  available.

Without this, the component cannot scan files by mme type.

I will not close the issue because I want to add additional verification and display a warning, above the field if these requirements are not met.
In truth, you are the first of the users of the extension with both features turned off, but you need to display a warning.

**Comment by joomlaphp** [comment]
Hi Igor,

Thank you very much. The problem has been fixed!
